export const CREATE_RECIPE = "CREATE_RECIPE";
export const RETRIEVE_RECIPE = "RETRIEVE_RECIPE";
export const UPDATE_RECIPE = "UPDATE_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE";
export const CREATE_RECIPE_BOOK = "CREATE_RECIPE_BOOK";
export const RETRIEVE_RECIPE_BOOK = "RETRIEVE_RECIPE_BOOK";
export const UPDATE_RECIPE_BOOK = "UPDATE_RECIPE_BOOK";
export const DELETE_RECIPE_BOOK = "DELETE_RECIPE_BOOK";

